name: SMPVisitor
version: ${project.version}
main: org.tfsmp.smpvisitor.SMPVisitor
api-version: 1.13
authors: [super]
description: Visit places all around the map!
commands:
  visit:
    description: Visit anywhere around the map!
    usage: /<command>
    aliases: [vis]
  visitorlocations:
    description: Create, remove, and clear visitor locations.
    usage: /<command> <add <identifier> <skullowner> <world> <x> <y> <z> <name...> | remove <identifier> | clear>
    aliases: [vls]